spring:

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true


logging:
  level:
    root: info
    org.springframework.security: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: mappings

server:
  port: 8484
  servlet:
    session:
      tracking-modes: cookie


dynamia:
  app:
    name: @project.name@
    defaultSkin: Green
    template: Dynamical
    defaultLogo: /zkau/web/images/logo.png
    defaultIcon: /zkau/web/images/icon.png
    basePackage: mybookstore
    shortName: Tools
    version: @project.version@
    description: @project.description@
    build: @timestamp@
    author: @author@
    url: @project.url@
    web-cache-enabled: false

